@url= http://localhost:3308

###

POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Renato Feleps",
    "email": "renato@gmail.com",
    "cpf": "10678456949",
    "password": "senha123",
    "role": "ADMIN",
    "address": {
        "street": "Rua Topava",
        "number": 566,
        "neighborhood": "Toronto",
        "city": "Balneário",
        "state": "SC"
    }
}

###

POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Felipe Feleps",
    "email": "felipe@gmail.com",
    "cpf": "20678456949",
    "password": "senha123",
    "role": "ENTREGADOR",
    "address": {
        "street": "Rua Topava",
        "number": 566,
        "neighborhood": "Toronto",
        "city": "Balneário",
        "state": "SC"
    }
}


###
# @name login

POST {{url}}/auth/session
Content-Type: application/json

{
    "cpf": "20678456949",
    "password": "senha123"
}

###

@token= {{login.response.body.access_token}}

###

POST {{url}}/recipients
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tafarel Ramalho",
    "address": {
        "street": "Rua Nunes",
        "number": 555,
        "neighborhood": "Toronto",
        "city": "Balneário",
        "state": "SC"
    }
}

###

POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "recipientId": 1
}

###

POST {{url}}/orders/withdrawn/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/orders/3
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/user/orders?quantityPerPage=1&&page=1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}
